# Generated by Django 4.2.5 on 2023-10-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webTjc', '0003_rename_email_register_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('your_email', models.EmailField(max_length=254)),
                ('message_body', models.TextField(max_length=500)),
            ],
        ),
    ]
