# Generated by Django 4.2.5 on 2023-10-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webTjc', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_body',
            field=models.CharField(max_length=500),
        ),
    ]
